name: Build and Test on PR or Main

on:
  workflow_run:
    workflows: ["Generate and Deploy Javadoc"]
    types:
      - completed

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean verify
        working-directory: ./adventure