name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # ====================================================================
      # STEP 1 (MODIFICATO): Eseguiamo Maven in modalità debug (-X)
      # Questo produrrà un log molto lungo, ma conterrà l'errore esatto se Maven fallisce.
      # ====================================================================
      - name: Generate Javadoc with Maven (DEBUG MODE)
        run: mvn clean javadoc:javadoc -X
        working-directory: ./adventure

      # ====================================================================
      # STEP 2 (NUOVO): Listiamo tutti i file nel workspace
      # Questo ci mostrerà SE e DOVE la cartella 'docs' è stata creata.
      # ====================================================================
      - name: See what was created (List all files)
        run: ls -R

      # ====================================================================
      # STEP 3 (NUOVO): Controlliamo cosa vede Git prima del commit
      # Questo ci dirà se Git ha rilevato nuovi file da committare.
      # ====================================================================
      - name: Check Git status before commit
        run: git status

      - name: Commit and push Javadoc
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add docs
          git diff-index --quiet HEAD || git commit -m "docs: Generate and update Javadoc [ci skip]"
          git push
