name: Generate and Deploy Javadoc

on:
  pull_request:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Javadoc with Maven
        run: mvn clean javadoc:javadoc
        working-directory: ./adventure

      - name: Move Javadoc to docs/javadoc folder
        run: |
          rm -rf docs/javadoc
          mkdir -p docs/javadoc
          cp -r adventure/docs/* docs/javadoc/

      - name: Commit and push Javadoc changes
        run: |
          set -e
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "docs: Update Javadoc [skip ci]"
            git push
          fi