name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Genera la Javadoc (nel tuo caso viene salvata in adventure/docs)
      - name: Generate Javadoc with Maven
        run: mvn clean javadoc:javadoc
        working-directory: ./adventure

      # 4. Copia la Javadoc in docs/javadoc
      - name: Move Javadoc to docs/javadoc folder
        run: |
          rm -rf docs/javadoc
          mkdir -p docs/javadoc
          cp -r adventure/docs/* docs/javadoc/

      # 5. Commit e push solo se ci sono modifiche
      - name: Commit and push Javadoc
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"

          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "docs: Update Javadoc [skip ci]"
            git push
          else
            echo "Nessuna modifica alla Javadoc."
          fi